### ISSUE TITLE
Compiling for UE4 - LinuxArm64 is not a valid platform name

### ISSUE THREAD

**Issue by dr-smgad** [IncantaGames/unreal-bp-file-sdk#3]
I am trying to compile this plugin with Unreal engine 4.25.0 running on Ubuntu 18.04 LTS Linux (x-64) platform. I am getting the below error during compilation as the supported Linux platform by your plugin description is LinuxArm64. Do you have any release/branch that supports Linux x-64?

![Screenshot 2022-11-23 160535](https://user-images.githubusercontent.com/80755241/203666329-d303be6c-0e40-4335-9f5d-beb7628ce4f9.jpg)

**Comment by mikeseese** [comment]
Ah, I should add this to the readme:

I've separated UE4 and UE5 plugin descriptors due to the differences in platforms. To compile this plugin for UE4, rename `FileSDK.uplugin` to `FileSDK.uplugin.ue5` (or delete it) and rename `FileSDK.uplugin.ue4` to `FileSDK.uplugin`.

The `Linux` platform should support x64. For ARM support on UE4, it's `LinuxAArch64` (which got renamed to `LinuxArm64` in UE5). Both of these are specified in the `FileSDK.uplugin.ue4` file.

**Comment by mikeseese** [comment]
Updated the readme! If you run into another issue, please open a new issue.
